# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8946805351eec8f2cb7c577e8682c2a6aee60a33cc777b79f58232aad989994af611da18790ad5fba0d41c790db795691fef6468503541ae5860310fb6369ed

test:
  secret_key_base: 8c33fd2b9acd39740324766b9129730bb779843c6ccc026b1e8b65275e1c220a644b3559fe04fd91601af281c362a1df4c09585f56526078100262567e9b66a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
